Confirmação de email funcionando
glob-gall/plataforma-investimento pull request #45
Opened 2023-04-21 21:17 UTC by PabloSSena

2023-04-21 23:28 UTC, dotpinheiro requested changes

2023-04-21 23:28 UTC, dotpinheiro commented on plataforma-back/pinvestback/settings.py
> +SITE_URL = "http://127.0.0.1:8000/api"
é interessante criar um arquivo .env com essas configurações de ambiente ao invés de deixarmos direto no código

2023-04-21 23:28 UTC, dotpinheiro commented on plataforma-back/pinvestback/settings.py
> +EMAIL_HOST_PASSWORD ='uhqyqwumtoxsxdpx'
O mesmo vale pra essas configurações, devemos colocar em um arquivo .env não versionado. Não podemos expor o usuário e senha do email no repositório senão qualquer pessoa com acesso consegue acessar o email.
Inclusive recomendo alterar a senha do email porquê já foi exposta

2023-04-21 23:28 UTC, dotpinheiro commented on plataforma-back/usuarios/migrations/0004_remove_usuario_is_email_verified.py
> +            name='is_email_verified',
Por quê existe uma migration que adiciona um campo e em seguida outra migration que remove a adição do campo?

2023-04-21 23:28 UTC, dotpinheiro commented on plataforma-back/usuarios/migrations/0005_usuario_is_email_virified.py
> +            field=models.BooleanField(default=False),
pra não ficar um monte de migrations que fazem a mesma coisa, dá pra removê-las e deixar uma única que adiciona o campo

2023-04-21 23:28 UTC, dotpinheiro commented on plataforma-back/usuarios/migrations/0009_remove_usuario_token_confirmacao.py
> +            name='token_confirmacao',
Nesse caso aqui tbm, ao invés de adicionar a migration que cria o campo e depois criar outra que remove dá pra apenas ignorar elas e remover do repositório. Assim os campos não serão criados

2023-04-22 15:15 UTC, PabloSSena commented on plataforma-back/usuarios/migrations/0009_remove_usuario_token_confirmacao.py
> +            name='token_confirmacao',
bele vou alterar sas coisas aí subo de novo

2023-04-26 03:14 UTC, dotpinheiro approved these changes

2023-04-26 17:36 UTC, merged